spring:
  application:
    name: service-registry

server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_HOSTNAME:eureka-0}
  client:
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA:false}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:false}
    service-url:
      #       defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
      #      defaultZone: http://localhost:8761
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761}