server:
  port: 8203

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: DOCTOR-SERVICE
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/doctors/**
          filters:
            - name: CircuitBreaker
              args:
                name: DOCTOR-SERVICE
                fallbackuri: forward:/doctorServiceFallBack
        - id: PATIENT-SERVICE
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/patients/**
          filters:
            - name: CircuitBreaker
              args:
                name: PATIENT-SERVICE
                fallbackuri: forward:/patientServiceFallBack
        - id: APPOINTMENT-SERVICE
          uri: lb://APPOINTMENT-SERVICE
          predicates:
            - Path=/appointments/**
          filters:
            - name: CircuitBreaker
              args:
                name: APPOINTMENT-SERVICE
                fallbackuri: forward:/appointmentServiceFallBack

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_HOSTNAME:eureka-0}
  client:
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA:false}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:false}
    service-url:
      #       defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
      #      defaultZone: http://localhost:8761
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761}