spring:
  application:
    name: patient-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/patient?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  port: 8202

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_HOSTNAME:eureka-0}
  client:
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA:false}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:false}
    service-url:
      #       defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
      #      defaultZone: http://localhost:8761
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761}